
import 'dotenv/config';
import mongoose from 'mongoose';
import { faker } from '@faker-js/faker';
import User from '../models/User';
import ClassLead from '../models/ClassLead';
import FinalClass from '../models/FinalClass';
import Payment from '../models/Payment';
import Tutor from '../models/Tutor';
import Manager from '../models/Manager';
import Coordinator from '../models/Coordinator';
import {
  USER_ROLES,
  BOARD_TYPE,
  TEACHING_MODE,
  CLASS_LEAD_STATUS,
  PAYMENT_STATUS,
  PAYMENT_TYPE,
  VERIFICATION_STATUS,
  FINAL_CLASS_STATUS
} from '../config/constants';

const uri = process.env.MONGODB_URI || process.env.DATABASE_URL || 'mongodb://localhost:27017/yourshikshak';

async function connect() {
  await mongoose.connect(uri);
  console.log('[seedAnalytics] Connected to MongoDB    ');
}

const SEED_TAG = 'Generated by seedAnalytics    ';
const SEED_DOMAIN = 'seed-analytics.com';

async function main() {
  await connect();

  // 1. Cleanup    
  console.log('[seedAnalytics] Cleaning up existing seeded data...    ');
  // Delete users by email domain pattern    
  await User.deleteMany({ email: new RegExp(`@${SEED_DOMAIN}$`, 'i') });
  await ClassLead.deleteMany({ notes: SEED_TAG });
  await FinalClass.deleteMany({ notes: SEED_TAG });
  await Payment.deleteMany({ notes: SEED_TAG });

  const GRADES = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'];
  const SUBJECTS = ['Math', 'Science', 'English', 'Physics', 'Chemistry', 'Biology'];

  // 2. Create Managers & Coordinators    
  console.log('[seedAnalytics] Creating staff...    ');
  const managers = [];
  for (let i = 0; i < 3; i++) {
    const u = await User.create({
      name: faker.person.fullName(),
      email: `manager${i}@${SEED_DOMAIN}`,
      password: 'Password@123',
      role: USER_ROLES.MANAGER,
      phone: faker.string.numeric(10),
      isActive: true
    });
    await Manager.create({ user: u._id, isActive: true });
    managers.push(u);
  }

  const coordinators = [];
  for (let i = 0; i < 5; i++) {
    const u = await User.create({
      name: faker.person.fullName(),
      email: `coord${i}@${SEED_DOMAIN}`,
      password: 'Password@123',
      role: USER_ROLES.COORDINATOR,
      phone: faker.string.numeric(10),
      isActive: true
    });
    await Coordinator.create({ user: u._id, isActive: true });
    coordinators.push(u);
  }

  // 3. Create Tutors    
  console.log('[seedAnalytics] Creating tutors...    ');
  const tutors = [];
  for (let i = 0; i < 20; i++) {
    const u = await User.create({
      name: faker.person.fullName(),
      email: `tutor${i}@${SEED_DOMAIN}`,
      password: 'Password@123',
      role: USER_ROLES.TUTOR,
      phone: faker.string.numeric(10),
      isActive: true
    });
    const t = await Tutor.create({
      user: u._id,
      verificationStatus: VERIFICATION_STATUS.VERIFIED,
      subjects: [faker.helpers.arrayElement(SUBJECTS)],
      preferredMode: faker.helpers.arrayElement(Object.values(TEACHING_MODE)),
    });
    tutors.push({ u, t });
  }

  // 4. Create Parents/Students & Leads    
  console.log('[seedAnalytics] Creating leads and parents...    ');
  const parents = [];
  for (let i = 0; i < 50; i++) {
    const u = await User.create({
      name: faker.person.fullName(),
      email: `parent${i}@${SEED_DOMAIN}`,
      password: 'Password@123',
      role: USER_ROLES.PARENT,
      phone: faker.string.numeric(10),
      isActive: true,
      createdAt: faker.date.past({ years: 1 })
    });
    parents.push(u);
  }

  const leads = [];
  for (let i = 0; i < 200; i++) {
    const parent = faker.helpers.arrayElement(parents);
    const createdAt = faker.date.past({ years: 1, refDate: parent.createdAt });
    const isConverted = faker.number.int({ min: 1, max: 10 }) > 4; // 60% conversion    
    
    const lead = await ClassLead.create({
      studentType: 'SINGLE',
      studentName: faker.person.fullName(),
      studentGender: faker.helpers.arrayElement(['M', 'F']),
      parentName: parent.name,
      parentPhone: parent.phone,
      parentEmail: parent.email,
      grade: faker.helpers.arrayElement(GRADES),
      subject: [faker.helpers.arrayElement(SUBJECTS)],
      board: faker.helpers.arrayElement(Object.values(BOARD_TYPE)),
      mode: faker.helpers.arrayElement(Object.values(TEACHING_MODE)),
      timing: 'Evening 5-7 PM    ',
      status: isConverted ? CLASS_LEAD_STATUS.CONVERTED : CLASS_LEAD_STATUS.REJECTED,
      createdBy: faker.helpers.arrayElement(managers)._id,
      notes: SEED_TAG,
      createdAt,
      updatedAt: isConverted ? new Date(createdAt.getTime() + 5 * 86400000) : createdAt
    });
    leads.push(lead);
  }

  // 5. Create Final Classes & Payments    
  console.log('[seedAnalytics] Creating classes and payment history...    ');
  const convertedLeads = leads.filter(l => l.status === CLASS_LEAD_STATUS.CONVERTED);
  
  for (let i = 0; i < convertedLeads.length; i++) {
    const lead = convertedLeads[i];
    const tutor = faker.helpers.arrayElement(tutors);
    const coord = faker.helpers.arrayElement(coordinators);
    const isChurned = faker.number.int({ min: 1, max: 10 }) < 3; // 20% churn    
    
    // Determine end date if churned
    const endDate = isChurned 
      ? new Date(lead.updatedAt.getTime() + faker.number.int({ min: 30, max: 180 }) * 86400000)
      : undefined;
      
    // Ensure endDate (updatedAt) is not in the future
    const realEndDate = endDate && endDate > new Date() ? new Date() : endDate;

    const finalClass = await FinalClass.create({
      className: `Class ${i} - ${lead.studentName}    `,
      classLead: lead._id,
      tutor: tutor.u._id,
      coordinator: coord._id,
      parent: lead.parentEmail ? (await User.findOne({ email: lead.parentEmail }))?._id : undefined,
      studentName: lead.studentName,
      studentGender: lead.studentGender,
      subject: lead.subject,
      grade: lead.grade,
      board: lead.board,
      mode: lead.mode,
      status: isChurned ? FINAL_CLASS_STATUS.CANCELLED : FINAL_CLASS_STATUS.ACTIVE,
      startDate: lead.updatedAt,
      tutorFees: 1500,
      parentFees: 3000,
      ratePerSession: 500,
      totalSessions: 24,
      convertedBy: lead.createdBy,
      convertedAt: lead.updatedAt, // KEY FIX: Set convertedAt to match simulation
      notes: SEED_TAG,
      updatedAt: isChurned ? realEndDate : new Date()
    });

    // Create a series of monthly payments    
    const numPayments = faker.number.int({ min: 1, max: 6 });
    for (let p = 0; p < numPayments; p++) {
      const paymentDate = new Date(finalClass.startDate!.getTime() + (p * 30 * 86400000));
      if (paymentDate > new Date()) break;

      // Fee Collection    
      await Payment.create({
        finalClass: finalClass._id,
        tutor: tutor.u._id,
        amount: 3000,
        currency: 'INR',
        status: PAYMENT_STATUS.PAID,
        paymentType: PAYMENT_TYPE.FEES_COLLECTED,
        paymentDate,
        dueDate: paymentDate,
        createdBy: lead.createdBy,
        notes: SEED_TAG,
        createdAt: paymentDate
      });

      // Tutor Payout    
      await Payment.create({
        finalClass: finalClass._id,
        tutor: tutor.u._id,
        amount: 1500,
        currency: 'INR',
        status: PAYMENT_STATUS.PAID,
        paymentType: PAYMENT_TYPE.TUTOR_PAYOUT,
        paymentDate: new Date(paymentDate.getTime() + 5 * 86400000), // Paid 5 days later    
        dueDate: paymentDate,
        createdBy: lead.createdBy,
        notes: SEED_TAG,
        createdAt: paymentDate
      });
    }
  }

  console.log('[seedAnalytics] Successfully seeded full analytics suite    ');
  await mongoose.disconnect();
}

main().catch(async (err) => {
  console.error('[seedAnalytics] Error    :', err);
  if (err.errors) {
    Object.keys(err.errors).forEach(key => {
      console.error(`- Field "${key}": ${err.errors[key].message}    `);
    });
  }
  await mongoose.disconnect();
  process.exit(1);
});
