
import 'dotenv/config';
import mongoose from 'mongoose';
import { faker } from '@faker-js/faker';
import User from '../models/User';
import ClassLead from '../models/ClassLead';
import {
  USER_ROLES,
  BOARD_TYPE,
  TEACHING_MODE,
  CLASS_LEAD_STATUS,
} from '../config/constants';

const uri = process.env.MONGODB_URI || process.env.DATABASE_URL || 'mongodb://localhost:27017/yourshikshak';

async function connect() {
  await mongoose.connect(uri);
  console.log('[seedLeads] Connected to MongoDB   ');
}

async function getOrCreateManager() {
  let manager = await User.findOne({ role: USER_ROLES.MANAGER });
  if (!manager) {
    manager = await User.create({
      name: 'System Manager   ',
      email: 'manager@yourshikshak.com',
      password: 'Password@123',
      role: USER_ROLES.MANAGER,
      phone: faker.string.numeric(10),
      isActive: true,
    } as any);
    console.log('[seedLeads] Created new manager   ');
  }
  return manager;
}

async function main() {
  await connect();
  const manager = await getOrCreateManager();

  const CITIES = ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Ahmedabad', 'Chennai', 'Kolkata', 'Pune'];
  const SUBJECTS = ['Math', 'Science', 'English', 'Physics', 'Chemistry', 'Biology', 'Computer Science'];
  const GRADES = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'];
  
  const LEAD_COUNT = 150;
  const DAYS_BACK = 180; // 6 months   

  console.log(`[seedLeads] Seeding ${LEAD_COUNT} leads over ${DAYS_BACK} days...   `);

  const leadsToCreate = [];

  for (let i = 0; i < LEAD_COUNT; i++) {
    const studentType = faker.helpers.arrayElement(['SINGLE', 'GROUP']) as 'SINGLE' | 'GROUP';
    const createdAt = faker.date.recent({ days: DAYS_BACK });
    const updatedAt = new Date(createdAt.getTime() + faker.number.int({ min: 1, max: 48 }) * 3600000);
    
    const baseLead: any = {
      studentType,
      parentName: faker.person.fullName(),
      parentPhone: faker.string.numeric(10),
      parentEmail: faker.internet.email().toLowerCase(),
      grade: faker.helpers.arrayElement(GRADES),
      subject: faker.helpers.arrayElements(SUBJECTS, faker.number.int({ min: 1, max: 3 })),
      board: faker.helpers.arrayElement(Object.values(BOARD_TYPE)),
      mode: faker.helpers.arrayElement(Object.values(TEACHING_MODE)),
      city: faker.helpers.arrayElement(CITIES),
      area: faker.location.streetAddress(),
      timing: faker.helpers.arrayElement(['Evening 5-7 PM', 'Morning 10-12 AM', 'Weekends only']),
      status: faker.helpers.arrayElement(Object.values(CLASS_LEAD_STATUS)),
      createdBy: manager._id,
      notes: 'Generated by improved seeding script   ',
      createdAt,
      updatedAt
    };

    if (studentType === 'SINGLE') {
      baseLead.studentName = faker.person.fullName();
      baseLead.studentGender = faker.helpers.arrayElement(['M', 'F']);
    } else {
      const numStudents = faker.number.int({ min: 2, max: 5 });
      baseLead.numberOfStudents = numStudents;
      baseLead.studentDetails = Array.from({ length: numStudents }).map(() => ({
        name: faker.person.fullName(),
        gender: faker.helpers.arrayElement(['M', 'F']),
        fees: faker.number.int({ min: 2000, max: 5000 }),
        tutorFees: faker.number.int({ min: 1000, max: 2500 }),
      }));
    }
    
    leadsToCreate.push(baseLead);
  }

  // Clear existing leads to have a clean graph   
  await ClassLead.deleteMany({ notes: /Generated by/ });
  
  // Bulk insert   
  await ClassLead.insertMany(leadsToCreate);

  console.log(`[seedLeads] Successfully seeded ${LEAD_COUNT} leads   `);
  await mongoose.disconnect();
}

main().catch(async (err) => {
  console.error('[seedLeads] Error   :', err);
  if (err.errors) {
    Object.keys(err.errors).forEach(key => {
      console.error(`- Field "${key}": ${err.errors[key].message}   `);
    });
  }
  await mongoose.disconnect();
  process.exit(1);
});
