export enum USER_ROLES {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  TUTOR = 'TUTOR',
  COORDINATOR = 'COORDINATOR',
  PARENT = 'PARENT',
  STUDENT = 'STUDENT',
}

export enum CLASS_LEAD_STATUS {
  // Initial / enquiry stages
  NEW = 'NEW',
  ENQUIRY = 'ENQUIRY',

  // Announcement & demo lifecycle
  ANNOUNCED = 'ANNOUNCED',
  DEMO_SCHEDULED = 'DEMO_SCHEDULED',
  DEMO_COMPLETED = 'DEMO_COMPLETED',
  DEMO_APPROVED_BY_PARENT = 'DEMO_APPROVED_BY_PARENT',
  DEMO_REJECTED_BY_PARENT = 'DEMO_REJECTED_BY_PARENT',
  TUTOR_NOT_FOUND_FOR_DEMO = 'TUTOR_NOT_FOUND_FOR_DEMO',
  PARENT_DIDNT_RESPOND = "PARENT_DIDNT_RESPOND",

  // Commercial outcome
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',

  // Conversion / closure
  CONVERTED = 'CONVERTED',
  REJECTED = 'REJECTED',
}

export enum DEMO_STATUS {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ATTENDANCE_STATUS {
  PENDING = 'PENDING',
  COORDINATOR_APPROVED = 'COORDINATOR_APPROVED',
  PARENT_APPROVED = 'PARENT_APPROVED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum STUDENT_ATTENDANCE_STATUS {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  NATIONAL_HOLIDAY = 'NATIONAL_HOLIDAY',
}

export enum PAYMENT_STATUS {
  PENDING = 'PENDING',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
}

export enum PAYMENT_METHOD {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  UPI = 'UPI',
  CHEQUE = 'CHEQUE',
  ONLINE = 'ONLINE',
}

export enum PAYMENT_TYPE {
  FEES_COLLECTED = 'FEES_COLLECTED',
  TUTOR_PAYOUT = 'TUTOR_PAYOUT',
  MISCELLANEOUS = 'MISCELLANEOUS',
  TUTOR_VERIFICATION_FEES = 'TUTOR_VERIFICATION_FEES',
}

export enum VERIFICATION_STATUS {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum TEACHING_MODE {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  HYBRID = 'HYBRID',
}

export enum BOARD_TYPE {
  CBSE = 'CBSE',
  ICSE = 'ICSE',
  STATE_BOARD = 'STATE_BOARD',
  IB = 'IB',
  IGCSE = 'IGCSE',
}

export enum EXTRACURRICULAR_ACTIVITY {
  // Sports
  CRICKET = 'CRICKET',
  FOOTBALL = 'FOOTBALL',
  BASKETBALL = 'BASKETBALL',
  BADMINTON = 'BADMINTON',
  TENNIS = 'TENNIS',
  TABLE_TENNIS = 'TABLE_TENNIS',
  SWIMMING = 'SWIMMING',
  ATHLETICS = 'ATHLETICS',
  VOLLEYBALL = 'VOLLEYBALL',
  HOCKEY = 'HOCKEY',
  CHESS = 'CHESS',
  MARTIAL_ARTS = 'MARTIAL_ARTS',
  YOGA = 'YOGA',
  GYMNASTICS = 'GYMNASTICS',
  
  // Performing Arts
  DANCE = 'DANCE',
  DRAMA = 'DRAMA',
  THEATRE = 'THEATRE',
  PUBLIC_SPEAKING = 'PUBLIC_SPEAKING',
  DEBATE = 'DEBATE',
  
  // Music
  VOCAL_MUSIC = 'VOCAL_MUSIC',
  INSTRUMENTAL_MUSIC = 'INSTRUMENTAL_MUSIC',
  GUITAR = 'GUITAR',
  PIANO = 'PIANO',
  DRUMS = 'DRUMS',
  VIOLIN = 'VIOLIN',
  FLUTE = 'FLUTE',
  
  // Visual Arts
  PAINTING = 'PAINTING',
  DRAWING = 'DRAWING',
  SKETCHING = 'SKETCHING',
  SCULPTURE = 'SCULPTURE',
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  CRAFTS = 'CRAFTS',
  
  // Technology & Innovation
  CODING = 'CODING',
  ROBOTICS = 'ROBOTICS',
  WEB_DEVELOPMENT = 'WEB_DEVELOPMENT',
  APP_DEVELOPMENT = 'APP_DEVELOPMENT',
  GAME_DEVELOPMENT = 'GAME_DEVELOPMENT',
  AI_ML = 'AI_ML',
  
  // Academic Clubs
  SCIENCE_CLUB = 'SCIENCE_CLUB',
  MATH_CLUB = 'MATH_CLUB',
  QUIZ_CLUB = 'QUIZ_CLUB',
  LITERATURE_CLUB = 'LITERATURE_CLUB',
  CREATIVE_WRITING = 'CREATIVE_WRITING',
  
  // Social & Leadership
  STUDENT_COUNCIL = 'STUDENT_COUNCIL',
  COMMUNITY_SERVICE = 'COMMUNITY_SERVICE',
  VOLUNTEERING = 'VOLUNTEERING',
  ENVIRONMENTAL_CLUB = 'ENVIRONMENTAL_CLUB',
  MODEL_UN = 'MODEL_UN',
  
  // Others
  GARDENING = 'GARDENING',
  COOKING = 'COOKING',
  FASHION_DESIGN = 'FASHION_DESIGN',
  JOURNALISM = 'JOURNALISM',
  FILM_MAKING = 'FILM_MAKING',
  ANIMATION = 'ANIMATION',
  OTHER = 'OTHER',
}

export enum LEAD_SOURCE {
  GOOGLE_PROFILE = 'GOOGLE_PROFILE',
  GOOGLE_SEARCH = 'GOOGLE_SEARCH',
  GOOGLE_ADS = 'GOOGLE_ADS',
  FACEBOOK = 'FACEBOOK',
  INSTAGRAM = 'INSTAGRAM',
  JUSTDIAL = 'JUSTDIAL',
  SULEKHA = 'SULEKHA',
  WORD_OF_MOUTH = 'WORD_OF_MOUTH',
  WALK_IN = 'WALK_IN',
  WEBSITE = 'WEBSITE',
  WHATSAPP = 'WHATSAPP',
  REFERRED = 'REFERRED',
  SITE = 'SITE',
  OTHER = 'OTHER',
}

export enum PREFERRED_TUTOR_GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  NO_PREFERENCE = 'NO_PREFERENCE',
}

export enum FINAL_CLASS_STATUS {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  PAUSED = 'PAUSED',
  CANCELLED = 'CANCELLED',
}

export enum TEST_STATUS {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REPORT_SUBMITTED = 'REPORT_SUBMITTED',
}

export enum TEST_TYPE {
  UNIT_TEST    = 'UNIT_TEST',
  CHAPTER_TEST = 'CHAPTER_TEST',
  MOCK_EXAM    = 'MOCK_EXAM',
  WEEKLY_QUIZ  = 'WEEKLY_QUIZ',
  PRACTICE     = 'PRACTICE',
}

export enum MANAGER_ACTION_TYPE {
  CREATE_CLASS_LEAD = 'CREATE_CLASS_LEAD',
  UPDATE_CLASS_LEAD = 'UPDATE_CLASS_LEAD',
  DELETE_CLASS_LEAD = 'DELETE_CLASS_LEAD',
  POST_ANNOUNCEMENT = 'POST_ANNOUNCEMENT',
  ASSIGN_DEMO = 'ASSIGN_DEMO',
  REASSIGN_DEMO = 'REASSIGN_DEMO',
  UPDATE_DEMO_STATUS = 'UPDATE_DEMO_STATUS',
  CONVERT_TO_FINAL_CLASS = 'CONVERT_TO_FINAL_CLASS',
  UPDATE_PAYMENT_STATUS = 'UPDATE_PAYMENT_STATUS',
  VERIFY_TUTOR = 'VERIFY_TUTOR',
  CREATE_COORDINATOR = 'CREATE_COORDINATOR',
  UPDATE_COORDINATOR = 'UPDATE_COORDINATOR',
  CHANGE_TUTOR = 'CHANGE_TUTOR',
  TUTOR_LEFT_MID_SESSION = 'TUTOR_LEFT_MID_SESSION',
  REPOST_AS_LEAD = 'REPOST_AS_LEAD',
}

export enum COORDINATOR_ACTION_TYPE {
  UPDATE_FINAL_CLASS = 'UPDATE_FINAL_CLASS',
  SCHEDULE_TEST = 'SCHEDULE_TEST',
  UPDATE_TEST = 'UPDATE_TEST',
  CANCEL_TEST = 'CANCEL_TEST',
  DELETE_TEST = 'DELETE_TEST',
  CREATE_ADVANCE_PAYMENT_FOR_CLASS = 'CREATE_ADVANCE_PAYMENT_FOR_CLASS',
}

export enum CHANGE_ACTION {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  STATUS_CHANGE = 'STATUS_CHANGE',
}

export enum TUTOR_TIER {
  BRONZE = 'BRONZE',
  SILVER = 'SILVER',
  GOLD = 'GOLD',
  PLATINUM = 'PLATINUM',
}

export enum FEEDBACK_RATING {
  EXCELLENT = 5,
  GOOD = 4,
  AVERAGE = 3,
  BELOW_AVERAGE = 2,
  POOR = 1,
}

export const UPLOAD_CONFIG = {
  MAX_FILE_SIZE: 10 * 1024 * 1024,
  ALLOWED_FILE_TYPES: ['image/jpeg', 'image/png', 'image/jpg', 'application/pdf', 'application/x-pdf', 'application/acrobat', 'application/vnd.pdf', 'text/pdf', 'text/x-pdf'],
  UPLOAD_DIR: './uploads/documents',
};

export const DOCUMENT_TYPES = [
  'AADHAAR',
  'CERTIFICATE',
  'EXPERIENCE_PROOF',
  'DEGREE',
  'PROFILE_PHOTO',
  'OTHER',
] as const;

export enum THEME_MODE {
  LIGHT = 'light',
  DARK = 'dark',
  SYSTEM = 'system',
}

export enum LANGUAGE {
  ENGLISH = 'en',
  HINDI = 'hi',
  SPANISH = 'es',
  FRENCH = 'fr',
}

export enum PROFILE_VISIBILITY {
  PUBLIC = 'public',
  PRIVATE = 'private',
  CONTACTS = 'contacts',
}

export const MOBILE_UPLOAD_CONFIG = {
  MAX_IMAGE_SIZE: 10 * 1024 * 1024,
  MAX_IMAGES_PER_UPLOAD: 5,
  ALLOWED_IMAGE_TYPES: ['image/jpeg', 'image/png', 'image/jpg', 'image/webp'],
  MAX_IMAGE_DIMENSION: 4096,
  THUMBNAIL_SIZE: 300,
  MOBILE_IMAGE_QUALITY: 85,
};

export const MOBILE_PAGINATION_DEFAULTS = {
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
  MIN_LIMIT: 5,
};

export enum DEVICE_TYPE {
  IOS = 'ios',
  ANDROID = 'android',
}

export const FCM_CONFIG = {
  MAX_TOKENS_PER_BATCH: 500,
  NOTIFICATION_PRIORITY: 'high',
  NOTIFICATION_TTL: 86400,
};

export const VERIFICATION_FEE_AMOUNT = process.env.VERIFICATION_FEE_AMOUNT ? Number(process.env.VERIFICATION_FEE_AMOUNT) : 500;

export const VERIFICATION_FEE_DEDUCT_AMOUNT = process.env.VERIFICATION_FEE_DEDUCT_AMOUNT
  ? Number(process.env.VERIFICATION_FEE_DEDUCT_AMOUNT)
  : VERIFICATION_FEE_AMOUNT + 200;
