export enum USER_ROLES {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  TUTOR = 'TUTOR',
  COORDINATOR = 'COORDINATOR',
  PARENT = 'PARENT',
}

export enum CLASS_LEAD_STATUS {
  NEW = 'NEW',
  ANNOUNCED = 'ANNOUNCED',
  DEMO_SCHEDULED = 'DEMO_SCHEDULED',
  DEMO_COMPLETED = 'DEMO_COMPLETED',
  CONVERTED = 'CONVERTED',
  REJECTED = 'REJECTED',
}

export enum DEMO_STATUS {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ATTENDANCE_STATUS {
  PENDING = 'PENDING',
  COORDINATOR_APPROVED = 'COORDINATOR_APPROVED',
  PARENT_APPROVED = 'PARENT_APPROVED',
  REJECTED = 'REJECTED',
}

export enum PAYMENT_STATUS {
  PENDING = 'PENDING',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
}

export enum PAYMENT_METHOD {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  UPI = 'UPI',
  CHEQUE = 'CHEQUE',
  ONLINE = 'ONLINE',
}

export enum VERIFICATION_STATUS {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum TEACHING_MODE {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  HYBRID = 'HYBRID',
}

export enum BOARD_TYPE {
  CBSE = 'CBSE',
  ICSE = 'ICSE',
  STATE_BOARD = 'STATE_BOARD',
  IB = 'IB',
  IGCSE = 'IGCSE',
}

export enum FINAL_CLASS_STATUS {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  PAUSED = 'PAUSED',
  CANCELLED = 'CANCELLED',
}

export enum TEST_STATUS {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REPORT_SUBMITTED = 'REPORT_SUBMITTED',
}

export enum MANAGER_ACTION_TYPE {
  CREATE_CLASS_LEAD = 'CREATE_CLASS_LEAD',
  UPDATE_CLASS_LEAD = 'UPDATE_CLASS_LEAD',
  DELETE_CLASS_LEAD = 'DELETE_CLASS_LEAD',
  POST_ANNOUNCEMENT = 'POST_ANNOUNCEMENT',
  ASSIGN_DEMO = 'ASSIGN_DEMO',
  REASSIGN_DEMO = 'REASSIGN_DEMO',
  UPDATE_DEMO_STATUS = 'UPDATE_DEMO_STATUS',
  CONVERT_TO_FINAL_CLASS = 'CONVERT_TO_FINAL_CLASS',
  UPDATE_PAYMENT_STATUS = 'UPDATE_PAYMENT_STATUS',
  VERIFY_TUTOR = 'VERIFY_TUTOR',
  CREATE_COORDINATOR = 'CREATE_COORDINATOR',
  UPDATE_COORDINATOR = 'UPDATE_COORDINATOR',
}

export enum TUTOR_TIER {
  BRONZE = 'BRONZE',
  SILVER = 'SILVER',
  GOLD = 'GOLD',
  PLATINUM = 'PLATINUM',
}

export enum FEEDBACK_RATING {
  EXCELLENT = 5,
  GOOD = 4,
  AVERAGE = 3,
  BELOW_AVERAGE = 2,
  POOR = 1,
}

export const UPLOAD_CONFIG = {
  MAX_FILE_SIZE: 5 * 1024 * 1024,
  ALLOWED_FILE_TYPES: ['image/jpeg', 'image/png', 'image/jpg', 'application/pdf'],
  UPLOAD_DIR: './uploads/documents',
};

export const DOCUMENT_TYPES = ['AADHAAR', 'CERTIFICATE', 'EXPERIENCE_PROOF', 'DEGREE', 'OTHER'] as const;
